language: go

branches:
  only:
    - master  # 设置自动化部署的源码分支

# cache this directory
cache:
  directories:
    # 主题没有更改时可以缓存
    - themes

before_install:
- export TZ='Asia/Shanghai'  # 设置时区

# 安装依赖组件
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_0.68.3_Linux-64bit.tar.gz
  - tar -xzvf hugo_0.68.3_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version
  - git log -p -2 | cat
  - commit_msg=$(git log -n1 --pretty=format:"%s")
  - git clone --recursive -b master https://${GH_APIKEY}@github.com/scott-wong/scott-wong.github.io.git public
  # - rm -rf public/*

script:
  - hugo
  # - cp CNAME public/
  - pushd public 
  - git add .
  - git commit -m "auto depoly ${commit_msg} "
  - git push
  - echo "depoly done"